name: Deploy to Yandex Object Storage

on:
  push:
    branches:
      - main   # или твоya рабочая ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Yandex Object Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SECOND }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SECOND }}
        run: |
          aws s3 sync ./build s3://xn--80ajibkpb2bpo.xn--p1ai             --endpoint-url https://storage.yandexcloud.net             --delete             --acl public-read             --cache-control "no-cache"